# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Lorcha
tagline:             'One hour per day'
url:                 http://lorcha.github.io/iblog/
paginate:            1
baseurl:             "http://lorcha.github.io/iblog/"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Lorcha
  url:               https://twitter.com
  email:             TT@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              github.com/lorcha/iblog

# Page list


pages_list:       
  #About: '/iblog/about/'
  Archive: '/iblog/archive/'
  Feed: '/iblog/atom.xml'
