# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Blog
tagline:             'One step at a time'
url:                 http://Lorcha.github.io/iblog/
paginate:            1
baseurl:             "http://Lorcha.github.io/iblog/"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              T T
  url:               https://twitter.com
  email:             TT@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              github.com/Lorcha/iblog

# Page list


pages_list:       
  About: '/blog/about/'
  Archive: '/blog/archive/'
  Feed: '/blog/atom.xml'
